app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Entry(db.Model):
    __tablename__ = 'entries'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(), nullable=False)
    body = db.Column(db.String(), nullable=False)

    def __repr___(self):
        return '<Entry {}>'.format(id)

app/models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Entry(db.Model):
    __tablename__ = 'entries'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(), nullable=False)
    body = db.Column(db.String(), nullable=False)

    def __repr___(self):
        return '<Entry {}>'.format(id)


class Fortune(db.Model):
    __tablename__ = 'fortunes'
    __table_args__ = (db.UniqueConstraint('date', 'sign', name='unique_idx_date_sign'), {})

    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date)
    sign = db.Column(db.String(), nullable=False)
    rank = db.Column(db.Integer, nullable=False)
    content = db.Column(db.String(), nullable=False)
    item = db.Column(db.String(), nullable=False)
    money = db.Column(db.Integer, nullable=False)
    job = db.Column(db.Integer, nullable=False)
    love = db.Column(db.Integer, nullable=False)
    total = db.Column(db.Integer, nullable=False)
    color = db.Column(db.String(), nullable=False)

    def __repr__(self):
        return '<Fortune {}>'.format(id)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired


class EntryForm(FlaskForm):
    title = StringField('タイトル', validators=[DataRequired()])
    body = TextAreaField('本文', validators=[DataRequired()])

app/__init__.py
from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from config import Config
from flask_migrate import Migrate
from app.models import db, Entry, Fortune

migrate = Migrate()
admin = Admin(name='flasknote', template_mode='bootstrap3')
admin.add_view(ModelView(Entry, db.session))
admin.add_view(ModelView(Fortune, db.session))


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
    migrate.init_app(app, db)
    admin.init_app(app)

    from app.main.routes import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/main/routes.py
from flask import Blueprint
from flask import render_template, redirect, url_for
from app.models import db, Entry
from app.main.forms import EntryForm

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/', methods=['GET', 'POST'])
def index():
    entries = Entry.query.all()
    form = EntryForm()
    if form.validate_on_submit():
        entry = Entry()
        entry.title = form.title.data
        entry.body = form.body.data
        db.session.add(entry)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('main/index.html', form=EntryForm(), entries=entries)


@bp.route('/fortune', methods=['GET'])
def fortune():
    # date =
    return render_template('main/fortune.html')

app/modules/fortune/__init__.py
import requests
import datetime
import json
from app.models import Fortune

# http://api.jugemkey.jp/api/horoscope/free/year/month/day
endpoint = 'http://api.jugemkey.jp/api/horoscope/free/'


def get_fortune(date=datetime.datetime.today()):
    date_str = date.strftime(endpoint + '{}/{}/{}'.format())
    response = requests.get(url=endpoint + '{}/{}/{}'.format())

app/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <title>{% block title %}Home{% endblock %} | Flasknote</title>
</head>
<body>
    {% block navbar %}
    <div class="navbar is-light" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="{{ url_for('main.index') }}">
                    <span class="title">FlaskNote</span>
                </a>
            </div>
            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <a href="{{ url_for('main.index') }}" class="navbar-item">Home</a>
                    <a href="{{ url_for('main.fortune')}}" class="navbar-item">Fortune</a>
                </div>
            </div>
            <div class="navbar-end"></div>
        </div>
    </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
    </body>
</html>

app/templates/main/fortune.html
{% extends "base.html" %}

{% block content %}

<div class="hero is-info">
    <div class="hero-body">
        <div class="container">
            <span class="title">Fortune</span>
        </div>
    </div>
</div>
<div class="container">
    <div class="section">
        <div class="tile is-ancestor">
            <div class="tile is-parent">
                <article class="tile is-child notification is-primary">
                <p class="title">One</p>
                <p class="subtitle">Top tile</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                <p class="title">Two</p>
                <p class="subtitle">With an image</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                <p class="title">Three</p>
                <p class="subtitle">With an image</p>
                </article>
            </div>
        </div>
        <div class="tile is-ancestor">
            <div class="tile is-parent">
                <article class="tile is-child notification is-primary">
                <p class="title">Four</p>
                <p class="subtitle">Top tile</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                <p class="title">Five</p>
                <p class="subtitle">With an image</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                <p class="title">Six</p>
                <p class="subtitle">With an image</p>
                </article>
            </div>
        </div>
        <div class="tile is-ancestor">
            <div class="tile is-parent">
                <article class="tile is-child notification is-primary">
                <p class="title">Seven</p>
                <p class="subtitle">Top tile</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                <p class="title">Eight</p>
                <p class="subtitle">With an image</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                <p class="title">Nine</p>
                <p class="subtitle">With an image</p>
                </article>
            </div>
        </div>
        <div class="tile is-ancestor">
            <div class="tile is-parent">
                <article class="tile is-child notification is-primary">
                <p class="title">Ten</p>
                <p class="subtitle">Top tile</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                <p class="title">Eleven</p>
                <p class="subtitle">With an image</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child notification is-info">
                <p class="title">Twelve</p>
                <p class="subtitle">With an image</p>
                </article>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/main/index.html
{% extends "base.html" %}

{% block content %}

<div class="hero is-info">
    <div class="hero-body">
        <div class="container">
            <span class="title">Entries</span>
        </div>
    </div>
</div>
<div class="container">
    <div class="entries">
        {% for entry in entries %}
        <div class="column is-full">
            <div class="card">
                <div class="card-header">
                    <span class="card-header-title">{{ entry.title | safe }}</span>
                </div>
                <div class="card-content">
                    <div class="content">
                        <p>
                            {{ entry.body | safe }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="section">
        <div class="entry-form">
            <form action="{{ url_for('main.index') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="field">
                    {{ form.title.label(class="label") }}
                    <div class="control">
                        {{ form.title(class="input", placeholder="タイトル") }}
                    </div>
                </div>
                <div class="field">
                    {{ form.body.label(class="label") }}
                    <div class="control">
                        {{ form.body(class="textarea", placeholder="本文を入力してください") }}
                    </div>
                </div>
                <div class="control">
                    <button type="submit" class="button is-primary">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock%}